### ISSUE TITLE
File Name Transliteration Not Done in the Markdown Code

### ISSUE THREAD

**Issue by jpfleury** [tovic/drag-and-drop-image-uploader-plugin-for-mecha-cms#1]
Example to reproduce the bug: drag and drop and image named `image (2).jpg`. The Markdown code automaticaly added in the textarea is:

```
![image (2).jpg](http://URL/cabinet/assets/image (2).jpg)
```

It doesn't work because the filename on the server is `/cabinet/assets/image-2.jpg`.

**Comment by taufik-nurrohman** [comment]
Fixed thanks!
